### ISSUE TITLE
Adding a new 'tag everyone' whatsapp bot [GSSOC '23]

### ISSUE THREAD

**Issue by anuraganand92** [neelshah2409/Bot-Collection#50]
### **Description:**

This GitHub issue proposes adding a **WhatsApp Group Tagging Bot** to the repository. The bot, developed in **Python** using **Selenium**, will automate the process of **tagging everyone in a WhatsApp group**.

### **Implementation:**

The bot will utilize **Selenium** for **web automation** and i**nteract with the WhatsApp web interface**. It will send a message that **tags all members** in the group, **saving time and effort**.

###  **Expected Outcome:**

The WhatsApp Group Tagging Bot will effectively **tag all members** in a WhatsApp group, **ensuring they receive a notification**. As the **GSSOC '23 contributor**, I will implement this feature and welcome any suggestions or enhancements to the bot's functionality.

**Comment by shrish-shete20** [comment]
Hi @anuraganand92, Would you assign me this issue under GSSOC?

**Comment by A15h** [comment]
I want to work on this issue and will add a 'tag everyone' whatsapp bot. Please assign this to me.

**Comment by neelshah2409** [comment]
@anuraganand92 Go ahead !!

**Comment by Naemerem** [comment]
How do I add this to my WhatsApp??

**Comment by Maryam4311** [comment]
Hello

**Comment by ajtazer** [comment]
<img width="591" alt="image" src="https://github.com/neelshah2409/Bot-Collection/assets/37796611/52ddb004-27b2-4ced-b187-8c43b4c822e5">
i updated the sleep to 30sec made sure all my chats were loaded by the time it did the operation, still it failed

```
> python3 tagall-bot.py
Traceback (most recent call last):
  File "/Users/tazer/Desktop/INNOVA/Bot-Collection/Whatsapp-bot/Tag-all-bot/tagall-bot.py", line 16, in <module>
    group_name = driver.find_element_by_xpath(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@title='Innova Event Discussion and Planning']"}
  (Session info: chrome=117.0.5938.88)
```

**Comment by nxwi** [comment]
same issue of @ajtazer

**Comment by Akojede70** [comment]
how can I do it in my ends here I am really interested

**Comment by Anyacry** [comment]
> ### **Description:**
> 
> This GitHub issue proposes adding a **WhatsApp Group Tagging Bot** to the repository. The bot, developed in **Python** using **Selenium**, will automate the process of **tagging everyone in a WhatsApp group**.
> 
> ### **Implementation:**
> 
> The bot will utilize **Selenium** for **web automation** and i**nteract with the WhatsApp web interface**. It will send a message that **tags all members** in the group, **saving time and effort**.
> 
> ###  **Expected Outcome:**
> 
> The WhatsApp Group Tagging Bot will effectively **tag all members** in a WhatsApp group, **ensuring they receive a notification**. As the **GSSOC '23 contributor**, I will implement this feature and welcome any suggestions or enhancements to the bot's functionality.

**Comment by Serinovita12** [comment]
someone can teach me how to set up this please :')

**Comment by Maymayycodes** [comment]
Hiii how do I get the bot on my WhatsApp please

**Comment by MiguelSantiagoCaffe** [comment]
me interesa

**Comment by aniks7146-ship-it** [comment]
> python3 tagall-bot.py
Traceback (most recent call last):
  File "/Users/tazer/Desktop/INNOVA/Bot-Collection/Whatsapp-bot/Tag-all-bot/tagall-bot.py", line 16, in <module>
    group_name = driver.find_element_by_xpath(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/opt/homebrew/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@title='Innova Event Discussion and Planning']"}
  (Session info: chrome=117.0.5938.88)

**Comment by aniks7146-ship-it** [comment]
WhatsApp group.tagall all members bot

**Comment by aniks7146-ship-it** [comment]
- > WhatsApp 

> [group.tagall](url) / .bot

**Comment by Preciouzspark** [comment]
I want WhatsApp tag bot

**Comment by Preciouzspark** [comment]
group.tagall/ .bot
